app1:
   environment:
    BUILDOUT_ZEO_ADDRESS: zeo:8100
    BUILDOUT_ZEO_CLIENT: 'True'
  tty: true
  image: eeacms/plone
  links:
  - 'zeo:zeo'
  stdin_open: true
loadbalancer:
  ports:
  - 10301:80
  tty: true
  image: rancher/load-balancer-service
  links:
  - app1:app1
  stdin_open: true
zeo:
  tty: true
  image: eeacms/zeoserver
  stdin_open: true
