.catalog:
  name: Plone # Name of the versioned template of the Catalog Entry 
  version: 1.0 # Version of the versioned template of the Catalog Entry 
  description: Plone is a free and open source content management system # Description of the versioned template of the Catalog Entry
  uuid: Plone-0 # Unique identifier to be used for upgrades. Please see note. 
app1:
  scale: 2
  health_check:
    port: 80
    interval: 2000
    unhealthy_threshold: 3
    response_timeout: 2000
    healthy_threshold: 2
loadbalancer:
  scale: 1
zeo:
  scale: 1
  health_check:
    port: 8100
    interval: 2000
    unhealthy_threshold: 3
    response_timeout: 2000
    healthy_threshold: 2
